[versions]
agp = "8.2.0"
firebaseAuth = "22.3.0"
firebaseFirestore = "24.9.1"
gson = "2.10.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
lottie = "5.2.0"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
navigationFragmentKtx = "2.7.5"
annotation = "1.6.0"
lifecycleLivedataKtx = "2.6.2"
lifecycleViewmodelKtx = "2.6.2"
ksp = "1.9.0-1.0.13"
dagger = "2.48"
glide = "4.16.0"
okhttp = "4.10.0"
playServicesAuth = "20.7.0"
retrofit = "2.9.0"
fragmentKtx = "1.1.0"
roomCompilerVersion = "2.6.1"
roomKtx = "2.6.1"
swiperefreshlayout = "1.2.0-alpha01"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompilerVersion" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-converter = {module="com.squareup.retrofit2:converter-gson",version.ref="retrofit"}
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-fragment-ktx = {module="androidx.fragment:fragment-ktx",version.ref= "fragmentKtx"}
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }

[bundles]
okhttp = ["okhttp-core", "okhttp-logging-interceptor"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationFragmentKtx" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }


